# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d6e9acd45150f5a3adce6a58f1c4cf98"
name = "popup-app"
handle = "popup-app-28"
application_url = "https://diversity-survivors-boutique-paths.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_discounts,write_price_rules"

[auth]
redirect_urls = [
  "https://diversity-survivors-boutique-paths.trycloudflare.com/auth/callback",
  "https://diversity-survivors-boutique-paths.trycloudflare.com/auth/shopify/callback",
  "https://diversity-survivors-boutique-paths.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[app_proxy]
url = "https://diversity-survivors-boutique-paths.trycloudflare.com/app/main"
subpath = "popup"
prefix = "apps"
